### ISSUE TITLE
TODO(Backend)

### ISSUE THREAD

**Issue by stanbar** [MarkuSchick/zk-swap-ai#7]
- [x] Deploy two ERC20 tokens.
- [x] Deploy two AMM with liquidity.
- [x] Backend: Create an nodejs project/expressjs.
- [x] Backend: Query AMMs from the blockchain
- [x] Backend: Accept the partial transaction op = {inToken, outToken, amount, minOut, nonce, signature(self)}.
- [x] Backend(Solver): Find optimal trade for the intent
~~Backend: /getNonce/:address~~
- [x] Backend->Module: tradeWithIntent
- [x] Circom: Write the circuit.
- [x] Circom: Deploy the verifier smart contract.
- [x] Circom: Generate the proof using [circomkit](https://github.com/erhant/circomkit).
- [x] Solidity: Deploy Safe 
- [x] Gnosis module: Write the Gnosis module smart contract. https://github.com/5afe/safe-core-protocol-demo/blob/main/contracts/contracts/Plugins.sol https://github.com/5afe/safe-cli
- [x] Backend: Submit the transaction to the gnosis module {op, solution, proof}.
- [x] Gnosis module: Validates data (user' op, backend's proof and solution).
- [x] Gnosis module: Execute transaction on the user's smart contract behalf.
